#!/usr/bin/env python3

CONFIG_PATH = "/home/amnesia/.config/gobby/config.xml"

CONFIG_CONTENT = """<?xml version="1.0" encoding="UTF-8"?>
<gobby-config>
  <initial>
    <run>1</run>
  </initial>
  <user>
    <allow-remote-access>0</allow-remote-access>
  </user>
</gobby-config>
"""


def main():
    with open(CONFIG_PATH, "w+") as f:
        f.write(CONFIG_CONTENT)

if __name__ == "__main__":
    main()
