#!/usr/bin/env python3

import sys
import dbus

# Main script
domain = sys.argv[1]
port = int(sys.argv[2])
username = sys.argv[3]
protocol = 'prpl-jabber'
jid = username + '@' + domain
bus = dbus.SessionBus()
purple = bus.get_object('im.pidgin.purple.PurpleService',
                        '/im/pidgin/purple/PurpleObject')
account = purple.PurpleAccountsFind(jid, protocol)
if not account:
    account = purple.PurpleAccountNew(jid, protocol)
    purple.PurpleAccountsAdd(account)
    purple.PurpleAccountSetBool(account, 'port', port)
    purple.PurpleAccountSetUsername(account, jid)
    purple.PurpleAccountSetBool(account, 'auth_plain_in_clear', 1)
    purple.PurpleAccountSetString(account, 'connection_security',
                                           'opportunistic_tls')
    purple.PurpleAccountSetString(account, 'ft_proxies', '')
    purple.PurpleAccountRegister(account)
purple.PurpleAccountSetEnabled(account, 'gtk-gaim', 1)
